makeall: clean all

clean:
	rm -rf server.out client.out

all:
	
	gcc -g -Wall server.c color_output.c scanbox.c  chat.c  epolll.c -o server.out
	


	gcc -g -Wall client.c color_output.c scanbox.c  chat.c  epolll.c -o client.out

